<div class="std">
    <style type="text/css">
        img:hover {
            -webkit-filter: grayscale(100%);
            filter: grayscale(100%);
        }
    </style>
    <div style="background-color: #e92d46; width: 100%; padding: 8px 20px 1px;">
        <p style="text-align: center; margin-bottom: 10px;"><strong><span style="font-size: xx-large; color: #ffffff;"><img src="https://www.rocketsciencesports.com/media/wysiwyg/custom-rss.png" alt="" class="custom-rss-img">SELECT YOUR LEVEL</span></strong></p>
    </div>
    <div style="text-align: center;">
        <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: top;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">ROCKET</p>
            <div style="margin: 10px;"><a href="/custom.php?s=level&amp;l=aero"><img src="https://www.rocketsciencesports.com/media/wysiwyg/rocket-bike.png" alt=""></a></div>
            <p style="font-size: 22px; text-align: left; padding: 10px;">Carbon technology
                Ultra light and breathable
                Tailored fit
            </p>
        </div>
        <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: top;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">ELITE</p>
            <div style="margin: 10px;"><a href="/custom.php?s=level&amp;l=elite3"><img src="https://www.rocketsciencesports.com/media/wysiwyg/elite-bike.png" alt=""></a></div>
            <p style="font-size: 22px; text-align: left; padding: 10px;">Quick dry
                Tailored fit
            </p>
        </div>
        <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: top;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">RJ</p>
            <div style="margin: 10px;"><a href="/custom.php?s=level&amp;l=rj"><img src="https://www.rocketsciencesports.com/media/wysiwyg/rj-bike.png" alt=""></a></div>
            <p style="font-size: 22px; text-align: left; padding: 10px;">Light and breathable&nbsp;
                Quick dry
            </p>
        </div>
    </div>
</div>