<div class="std"><style type="text/css">
        img:hover {
            -webkit-filter: grayscale(100%);
            filter: grayscale(100%);
        }
    </style>
    <div style="background-color: #e92d46; width: 100%; padding: 8px 20px 1px;">
        <p style="text-align: center; margin-bottom: 10px;"><strong><span style="font-size: xx-large; color: #ffffff;"><img src="https://www.rocketsciencesports.com/media/wysiwyg/custom-rss.png" alt="" class="custom-rss-img">SELECT YOUR SPORT</span></strong></p>
    </div>
    <div style="text-align: center;">
        <div style="margin: 20px; display: inline-block;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Triathlon</p>
            <div style="margin: 10px;"><a href="/custom-order/sport/triathlon"><img alt="" src="https://www.rocketsciencesports.com/media/wysiwyg/Triathlon.png"></a></div>
        </div>
        <div style="margin: 20px; display: inline-block;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Swimming</p>
            <div style="margin: 10px;"><a href="/custom-order/sport/swimming"><img style="width:260px;" alt="" src="https://www.rocketsciencesports.com/media/wysiwyg/swimming-image.png"></a></div>
        </div>
        <div style="margin: 20px; display: inline-block;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Swim Caps</p>
            <div style="margin: 10px;"><a href="/custom-order/sport/swimcaps"><img alt="" src="https://www.rocketsciencesports.com/media/wysiwyg/Swimming.png"></a></div>
        </div>
        <div style="margin: 20px; display: inline-block;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Cycling</p>
            <div style="margin: 10px;"><a href="/custom-order/sport/cycling"><img alt="" src="https://www.rocketsciencesports.com/media/wysiwyg/Cycling.png"></a></div>
        </div>
        <div style="margin: 20px; display: inline-block;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Running</p>
            <div style="margin: 10px;"><a href="/custom-order/sport/running"><img alt="" src="https://www.rocketsciencesports.com/media/wysiwyg/Running.png"></a></div>
        </div>
        <div style="margin: 20px; display: inline-block;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Apparel</p>
            <div style="margin: 10px;"><a href="/custom-order/sport/apparel"><img alt="" src="https://www.rocketsciencesports.com/media/wysiwyg/Gym.png"></a></div>
        </div>
        <div style="margin: 20px; display: inline-block;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Yoga</p>
            <div style="margin: 10px;"><a href="/custom-order/sport/yoga"><img alt="" src="https://www.rocketsciencesports.com/media/wysiwyg/Yoga.png"></a></div>
        </div>
        <div style="margin: 20px; display: inline-block;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Basketball</p>
            <div style="margin: 10px;"><a href="/custom-order/sport/basketball"><img alt="" src="https://www.rocketsciencesports.com/media/wysiwyg/Basketball.png"></a></div>
        </div>
        <div style="margin: 20px; display: inline-block;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Soccer</p>
            <div style="margin: 10px;"><a href="/custom-order/sport/soccer"><img alt="" src="https://www.rocketsciencesports.com/media/wysiwyg/Soccer.png"></a></div>
        </div>
        <div style="margin: 20px; display: inline-block;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Volleyball</p>
            <div style="margin: 10px;"><a href="/custom-order/sport/volleyball"><img alt="" src="https://www.rocketsciencesports.com/media/wysiwyg/Volleyball.png"></a></div>
        </div>
        <div style="margin: 20px; display: inline-block;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Tennis</p>
            <div style="margin: 10px;"><a href="/custom-order/sport/tennis"><img alt="" src="https://www.rocketsciencesports.com/media/wysiwyg/Tennis.png"></a></div>
        </div>
        <div style="margin: 20px; display: inline-block;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Rugby</p>
            <div style="margin: 10px;"><a href="/custom.php?s=sport&amp;sp=rugby"><img alt="" src="https://www.rocketsciencesports.com/media/wysiwyg/Rugby.png"></a></div>
        </div>
        <div style="margin: 20px; display: inline-block;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Underwater Hockey</p>
            <div style="margin: 10px;"><a href="/custom-order/sport/underwater-hockey"><img style="width:260px;" alt="" src="https://www.rocketsciencesports.com/media/wysiwyg/underwater-hockey.png"></a></div>
        </div>
        <div style="margin: 20px; display: inline-block;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">PE</p>
            <div style="margin: 10px;"><a href="/custom-order/sport/pe"><img alt="" src="https://www.rocketsciencesports.com/media/wysiwyg/pe_1.png"></a></div>
        </div>
        <div style="margin: 20px; display: inline-block;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Water Polo</p>
            <div style="margin: 10px;"><a href="/custom-order/sport/water-polo"><img alt="" src="https://www.rocketsciencesports.com/media/wysiwyg/Screenshot_1.png"></a></div>
        </div>
    </div></div>