<div class="std">
    <style type="text/css">
        img:hover {
            -webkit-filter: grayscale(100%);
            filter: grayscale(100%);
        }
    </style>
    <div style="background-color: #e92d46; width: 100%; padding: 8px 20px 1px;">
        <p style="text-align: center; margin-bottom: 10px;"><strong><span style="font-size: xx-large; color: #ffffff;"><img src="https://www.rocketsciencesports.com/media/wysiwyg/custom-rss.png" alt="" class="custom-rss-img">SELECT YOUR PE PRODUCTS</span></strong></p>
    </div>
    <div style="text-align: center;">
        <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: bottom;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Tech-T</p>
            <div style="margin: 10px;"><a href="/custom.php?s=product&amp;p=tech-t"><img src="https://www.rocketsciencesports.com/media/wysiwyg/Picture30.jpg" alt=""></a></div>
            <p style="font-size: 22px; text-align: left; padding: 10px;"></p>
        </div>

        <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: bottom;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Long Sleeve Tech-T</p>
            <div style="margin: 10px;"><a href="/custom.php?s=product&amp;p=long-sleeve-tech-t"><img src="https://www.rocketsciencesports.com/media/wysiwyg/Picture29.jpg" alt=""></a></div>
            <p style="font-size: 22px; text-align: left; padding: 10px;"></p>
        </div>

        <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: bottom;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Jacket</p>
            <div style="margin: 10px;"><a href="/custom.php?s=product&amp;p=jacket"><img src="https://www.rocketsciencesports.com/media/wysiwyg/Picture42.jpg" alt=""></a></div>
            <p style="font-size: 22px; text-align: left; padding: 10px;"></p>
        </div>

        <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: bottom;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Hoodie</p>
            <div style="margin: 10px;"><a href="/custom.php?s=product&amp;p=hoodie"><img src="https://www.rocketsciencesports.com/media/wysiwyg/Picture41.jpg" alt=""></a></div>
            <p style="font-size: 22px; text-align: left; padding: 10px;"></p>
        </div>

        <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: bottom;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Jacket with Hood</p>
            <div style="margin: 10px;"><a href="/custom.php?s=product&amp;p=jacket-with-hood"><img src="https://www.rocketsciencesports.com/media/wysiwyg/Picture39.jpg" alt=""></a></div>
            <p style="font-size: 22px; text-align: left; padding: 10px;"></p>
        </div>

        <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: bottom;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Shorts</p>
            <div style="margin: 10px;"><a href="/custom.php?s=product&amp;p=shorts"><img src="https://www.rocketsciencesports.com/media/wysiwyg/Picture35.jpg" alt=""></a></div>
            <p style="font-size: 22px; text-align: left; padding: 10px;"></p>
        </div>

        <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: bottom;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Warm Up Pants</p>
            <div style="margin: 10px;"><a href="/custom.php?s=product&amp;p=pants"><img src="https://www.rocketsciencesports.com/media/wysiwyg/Picture43.jpg" alt=""></a></div>
            <p style="font-size: 22px; text-align: left; padding: 10px;"></p>
        </div>

        <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: bottom;">
            <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Coaches Polo</p>
            <div style="margin: 10px;"><a href="/custom.php?s=product&amp;p=polo"><img src="https://www.rocketsciencesports.com/media/wysiwyg/Picture34.jpg" alt=""></a></div>
            <p style="font-size: 22px; text-align: left; padding: 10px;"></p>
        </div>
    </div>
</div>