<div class="std">
    <style type="text/css">
        img:hover {
            -webkit-filter: grayscale(100%);
            filter: grayscale(100%);
        }
        .custom-continue {
            text-align: right;
            margin: 40px;
        }
        .custom-continue a {
            color: #e92d46;
            font-size: 32px;
            text-decoration: none;
        }
        .custom-continue a:hover {
            text-decoration: underline;
        }
    </style>
    <div style="background-color: #e92d46; width: 100%; padding: 8px 20px 1px;">
        <p style="text-align: center; margin-bottom: 10px;"><strong><span style="font-size: xx-large; color: #ffffff;"><img src="https://www.rocketsciencesports.com/media/wysiwyg/custom-rss.png" alt="" class="custom-rss-img">SELECT YOUR SWIM CAP</span></strong></p>
    </div>
    <div style="text-align: center;">
        <form action="/custom.php?s=product" method="POST" id="form">
            <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: bottom;">
                <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Dome Cap<br>85g</p>
                <div style="margin: 10px;"><a href="javascript:void(0)"><img src="https://www.rocketsciencesports.com/media/wysiwyg/Picture15.jpg" alt="" onclick="productSelect(this, 'Dome Cap');"></a></div>
                <p style="font-size: 22px; text-align: left; padding: 10px;"></p>
            </div>
            <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: bottom;">
                <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Classic Cap<br>60g</p>
                <div style="margin: 10px;"><a href="javascript:void(0)"><img src="https://www.rocketsciencesports.com/media/wysiwyg/Picture16.jpg" alt="" onclick="productSelect(this, 'Classic Cap');"></a></div>
                <p style="font-size: 22px; text-align: left; padding: 10px;"></p>
            </div>
            <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: bottom;">
                <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Seamless Cap<br>60g</p>
                <div style="margin: 10px;"><a href="javascript:void(0)"><img src="https://www.rocketsciencesports.com/media/wysiwyg/Picture17.jpg" alt="" onclick="productSelect(this, 'Seamless Cap');"></a></div>
                <p style="font-size: 22px; text-align: left; padding: 10px;"></p>
            </div>
            <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: bottom;">
                <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Light Weight Cap<br>38g</p>
                <div style="margin: 10px;"><a href="javascript:void(0)"><img src="https://www.rocketsciencesports.com/media/wysiwyg/Picture18.jpg" alt="" onclick="productSelect(this, 'Light Weight Cap');"></a></div>
                <p style="font-size: 22px; text-align: left; padding: 10px;"></p>
            </div>
            <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: bottom;">
                <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Latex Cap<br>25g</p>
                <div style="margin: 10px;"><a href="javascript:void(0)"><img src="https://www.rocketsciencesports.com/media/wysiwyg/Picture19.jpg" alt="" onclick="productSelect(this, 'Latex Cap');"></a></div>
                <p style="font-size: 22px; text-align: left; padding: 10px;"></p>
            </div>

            <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: bottom;">
                <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Long Hair Cap<br>60g</p>
                <div style="margin: 10px;"><a href="javascript:void(0)"><img src="https://www.rocketsciencesports.com/media/wysiwyg/long-hair-new2.jpg" alt="" onclick="productSelect(this, 'Long Hair Cap');"></a></div>
                <p style="font-size: 22px; text-align: left; padding: 10px;"></p>
            </div>

            <div style="margin: 20px; display: inline-block; max-width: 221px; vertical-align: bottom;">
                <p style="margin: 10px; font-size: 28px; color: #777; text-align: center;">Water Polo Cap</p>
                <div style="margin: 10px;"><a href="javascript:void(0)"><img src="https://www.rocketsciencesports.com/media/wysiwyg/Picture20.jpg" alt="" onclick="productSelect(this, 'Water Polo Cap');"></a></div>
                <p style="font-size: 22px; text-align: left; padding: 10px;"></p>
            </div>

            <input type="hidden" name="products" id="products">
            <div class="custom-continue">
                <a href="javascript:void(0)" onclick="document.getElementById('form').submit()">CONTINUE</a>
            </div>
        </form>
    </div>
    <script type="text/javascript">
        var products = document.getElementById('products');
        function productSelect(el, product) {
            remove = false;
            if (el.style.border == '') {
                el.style.border = "8px solid #e92d46";
                el.style.padding = "3px";
            } else {
                el.style.border = "";
                el.style.padding = "0px";
                remove = true;
            }
            if (products.value == '') {
                products.value = product;
            } else {
                if (remove) {
                    products.value = products.value.replace(product, "");
                } else {
                    products.value = products.value + " | " + product;
                }
            }
        }
    </script></div>