<?= $block->getChildHtml('tax.mapping.switcher'); ?>
<br />
<br />
<br />
<br />
<?php
/** @var Magenest\Xero\Block\Adminhtml\Xero\Tax $block */
$taxes = $block->getTaxes();
if (!is_array($taxes)):?>
    <span class="title" style="font-size: 11pt; font-weight: normal; font-style: italic">
     <?= $block->escapeHtml(__($taxes)) ?>
    </span>
<?php else: ?>
    <section class="admin__page-section order-view-billing-shipping">

        <div class="admin__page-section-content" style="width: 100%;">
            <div class="admin__page-section-item order-payment-method admin__fieldset-wrapper" style="width: 100%;">
                <div class="admin__page-section-item-title" style="width: 100%;">
                <span class="title" style="font-size: 11pt; font-weight: normal; font-style: italic">
                    <?= $block->escapeHtml(__('(Tax method will be converted to the corresponding Xero tax.
                     Only enabled Tax method will display here.)')) ?>
                </span>
                </div>
                <div class="admin__page-section-item-content" style="width: 100%;">
                    <button id="submit_mapping" style="width: 25%; margin-right: 20%;">Save Mapping</button>
                    <button id="update_tax_rates" style="width: 25%;">Update Tax Rates</button>
                    <form id="mapping_form">
                        <table class="admin__table-secondary">
                            <thead>
                            <th>ID</th>
                            <th>Tax Identifier</th>
                            <th>Country</th>
                            <th>Xero Tax</th>
                            </thead>
                            <tbody>
                            <input name="form_key" type="hidden"
                                   value="<?= $block->escapeHtml($block->getFormKey()) ?>"/>
                            <input name="website_id" type="hidden"
                                   value="<?= $block->escapeHtml($block->getWebsiteId()) ?>" />
                            <?php foreach ($block->getTaxRates() as $code => $rate): ?>
                                <?php $selectedAcc = $block->getSelectedMapping($code) ?>
                                <tr>
                                    <td><?= $block->escapeHtml(isset($rate['tax_calculation_rate_id']) ?
                                            $rate['tax_calculation_rate_id'] : $code) ?></td>
                                    <td><?= $block->escapeHtml($code) ?></td>
                                    <td><?= $block->escapeHtml($rate['tax_country_id']) ?></td>
                                    <?php
                                    // @codingStandardsIgnoreStart
                                    ?>
                                    <td><select class="admin__control-select"
                                                style="width: 400px; height: 30px;"
                                                name="taxRateMapping<?= $block->escapeHtml("[{$code}]") ?>"
                                        >
                                            <option value="null">Default Tax in Sale Account
                                                (in Stores/Configuration)</option>
                                            <?php foreach ($taxes as $tax): ?>
                                                <option value="<?= $block->escapeHtml($tax['TaxType']) ?>"
                                                    <?= $block->escapeHtml($tax['TaxType'] == $selectedAcc ? 'selected' : '') ?>>
                                                    <?= $block->escapeHtml(isset($tax['TaxType']) ? "[{$tax['TaxType']}] " : '');?>
                                                    <?= $block->escapeHtml($tax['Name'])?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>
