<!--<div class="block block-collapsible-nav">-->
<!--    <div class="title block-collapsible-nav-title">-->
<!--        <strong>--><?php //echo __('My Affiliate Account'); ?><!--</strong>-->
<!--    </div>-->
<!--    <div class="content block-collapsible-nav-content" id="block-collapsible-nav">-->
<!--        <ul class="nav items">-->
<!--            --><?php //echo $block->getChildHtml();?>
<!--        </ul>-->
<!--    </div>-->
<!--</div>-->


<div class="block account-nav">
    <div class="title account-nav-title">
        <strong></strong>
    </div>
    <div id="account-nav" class="content account-nav-content">
        <ul class="nav items affiliate-items">
            <?php echo $block->getChildHtml();?>
        </ul>
    </div>
</div>

<style>
    .account-nav .content{
        background-color: #f5f5f5 !important;
        padding: 15px 0;
    }
    .affiliate-items{
        margin-left: 20px;
    }
</style>