<?php
namespace Magenest\Xero\Controller\Adminhtml\MassQueue;

use Magenest\Xero\Model\QueueFactory;
use Magento\Framework\App\Action\Action;
use Magento\Framework\App\Action\Context;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\Controller\ResultFactory;
use Magento\Ui\Component\MassAction\Filter;
use \Magento\Framework\Data\Collection\AbstractDb;

abstract class AbstractMassQueue extends Action
{
    protected $_config;

    protected $_filter;

    protected $_type;

    protected $_enable = "";

    protected $_collectionFactory;

    protected $_queueFactory;

    protected $_id;

    public function __construct(
        Context $context,
        ScopeConfigInterface $config,
        Filter $filter,
        QueueFactory $queueFactory,
        AbstractDb $collectionFactory
    ) {
        $this->_config = $config;
        $this->_filter = $filter;
        $this->_queueFactory = $queueFactory;
        $this->_collectionFactory = $collectionFactory;
        parent::__construct($context);
    }

    /**
     * @param RequestInterface $request
     * @return \Magento\Framework\App\ResponseInterface|\Magento\Framework\Controller\ResultInterface
     * @throws \Magento\Framework\Exception\NotFoundException
     */
    public function dispatch(RequestInterface $request)
    {
        $enable = $this->_config->getValue($this->_enable);
        if ($enable) {
            return parent::dispatch($request); // TODO: Change the autogenerated stub
        } else {
            return $this->handleUnauthorizedRequest();
        }
    }

    protected function handleUnauthorizedRequest()
    {
        if ($this->getRequest()->isAjax()) {
            $result = [
                'error' => true,
                'msg' => 'We could not handle your request. Please try again!'
            ];
            $response = $this->resultFactory->create(ResultFactory::TYPE_JSON);
            $response->setData($result);
            return $response;
        }
        $this->messageManager->addError('We could not handle your request. Please try again!');
        $resultRedirect = $this->resultFactory->create(ResultFactory::TYPE_REDIRECT);
        $resultRedirect->setUrl($this->_redirect->getRefererUrl());
        return $resultRedirect;
    }

    public function execute()
    {
        // TODO: Implement execute() method.
        $collection = $this->_filter->getCollection($this->_collectionFactory);

        $queueModel = $this->_queueFactory->create();
        $connection = $queueModel->getResource()->getConnection();
        $queueTable = $queueModel->getResource()->getMainTable();

        $records = [];
        $count = 0;
        $lastId = $collection->getLastItem()->getData($this->_id);

        $deleteIds = [];
        foreach ($collection as $item) {
            $records[] = [
                'type' => $this->_type,
                'entity_id' => $item->getData($this->_id),
                'enqueue_time' => new \Zend_Db_Expr('CURRENT_TIMESTAMP'),
                'priority' => 1
            ];
            $deleteIds[] = $item->getData($this->_id);
            $count++;
            if ($count > 5000 || $item->getData($this->_id) == $lastId) {
                $idsString = $connection->quoteInto('entity_id IN (?)', $deleteIds);
                $connection->delete($queueTable, "{$idsString} AND type like '{$this->_type}'");
                $connection->insertMultiple($queueTable, $records);
                $records = [];
                $count = 0;
            }
        }
        $this->messageManager->addSuccessMessage(
            __('A total of %1 record(s) have been add to queue.', $collection->getSize())
        );
    }
}
