<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
 *
 * @var $block \Magento\Customer\Block\Form\Register
 */
?>

<?php
// Get Affiliate information
$_dataHelper = $this->helper('MW\Affiliate\Helper\Data');
$isEnabled = $_dataHelper->moduleEnabled();
if ($isEnabled) {
    $showSignupAffiliate = (int) $_dataHelper->getShowSignUpFormAffiliateRegister();
    $cookie = (int) $_dataHelper->getCookie('customer');
    $referralCode = '';
    $bankCountry = '';
    $paymentGateway = '';
    $autoWithdrawn = '';
    $paymentEmail = '';
    $withdrawnLevel = '';
    $reserveLevel = '';
    $bankName = '';
    $nameAccount = '';
    $swiftBic = '';
    $referralSite = '';

    if ($cookie) {
        $affiliateCustomer = $_dataHelper->getAffiliateMemberById($cookie);
        if ($affiliateCustomer->getActive() == \MW\Affiliate\Model\Statusactive::ACTIVE
            && $affiliateCustomer->getStatus() == \MW\Affiliate\Model\Statusreferral::ENABLED
        ) {
            $referralCode = $affiliateCustomer->getReferralCode();
        }
    }

    $session = $_dataHelper->getCustomerSession();
    $checkAffiliate = $session->getCheckAffiliate();
    if (!$checkAffiliate) {
        $session->unsetData('check_affiliate');
        $session->unsetData('payment_gateway');
        $session->unsetData('payment_email');
        $session->unsetData('auto_withdrawn');
        $session->unsetData('withdrawn_level');
        $session->unsetData('reserve_level');
        $session->unsetData('bank_name');
        $session->unsetData('name_account');
        $session->unsetData('bank_country');
        $session->unsetData('swift_bic');
        $session->unsetData('referral_site');
    }

    if (isset($checkAffiliate) && $showSignupAffiliate == 2) {
        $paymentGateway = $session->getPaymentGateway();
        $paymentEmail = $session->getPaymentEmail();
        $autoWithdrawn = $session->getAutoWithdrawn();

        if ($autoWithdrawn == \MW\Affiliate\Model\Autowithdrawn::MANUAL) {
            $session->unsetData('withdrawn_level');
        }

        $withdrawnLevel = $session->getWithdrawnLevel();
        $reserveLevel = $session->getReserveLevel();
        $bankName = $session->getBankName();
        $nameAccount = $session->getNameAccount();
        $bankCountry = $session->getBankCountry();
        $swiftBic = $session->getSwiftBic();
        $referralSite = $session->getReferralSite();
    }
}
?>

<?php echo $block->getChildHtml('form_fields_before')?>
<?php /* Extensions placeholder */ ?>
<?php echo $block->getChildHtml('customer.form.register.extra')?>
<form class="form create account form-create-account" action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <fieldset class="fieldset create info">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Personal Information') ?></span></legend><br>
        <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
        <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
        <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
        <div class="field required">
            <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email_address" value="<?php echo $block->escapeHtml($block->getFormData()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>

        <?php if ((int) $_dataHelper->getShowReferralCodeRegister()) : ?>
            <div class="field">
                <label for="referral_code" class="label"><span><?php echo __('Referral Code') ?></span></label>
                <div class="control">
                    <input type="text" name="referral_code" id="referral_code" value="<?php echo $referralCode; ?>" title="<?php echo __('Referral Code') ?>" class="input-text" />
                </div>
            </div>
        <?php endif; ?>

        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="field choice newsletter">
                <input type="checkbox" name="is_subscribed" title="<?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
                <label for="is_subscribed" class="label"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?></span></label>
            </div>
            <?php /* Extensions placeholder */ ?>
            <?php echo $block->getChildHtml('customer.form.register.newsletter')?>
        <?php endif ?>

        <?php if ($showSignupAffiliate == 1): ?>
            <div class="field choice check_affiliate">
                <input type="checkbox" id="check_affiliate"<?php if ($checkAffiliate): ?> checked="checked"<?php endif; ?> name="check_affiliate" title="<?php echo __('Sign up for our Affiliate Program') ?>" class="checkbox" />
                <label for="check_affiliate" class="label"><span><?php echo __('Sign up for our Affiliate Program') ?></span></label>
            </div>
        <?php endif; ?>

        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?php echo $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
        <?php endif ?>

        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?php echo $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
        <?php endif ?>

        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <?php echo $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
        <?php endif ?>
    </fieldset>
    <?php if ($block->getShowAddressFields()): ?>
        <fieldset class="fieldset address">
            <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Address Information') ?></span></legend><br>
            <input type="hidden" name="create_address" value="1" />
            <div class="field company">
                <label for="company" class="label"><span><?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
                <div class="control">
                    <input type="text" name="company" id="company" value="<?php echo $block->escapeHtml($block->getFormData()->getCompany()) ?>" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
                </div>
            </div>
            <div class="field telephone">
                <label for="telephone" class="label"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
                <div class="control">
                    <input type="text" name="telephone" id="telephone" value="<?php echo $block->escapeHtml($block->getFormData()->getTelephone()) ?>" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>">
                </div>
            </div>

            <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

            <div class="field street required">
                <label for="street_1" class="label"><span><?php /* @escapeNotVerified */ echo __('Street Address') ?></span></label>
                <div class="control">
                    <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getFormData()->getStreet(0)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" id="street_1" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                    <div class="nested">
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                            <div class="field additional">
                                <label class="label" for="street_<?php /* @escapeNotVerified */ echo $_i ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Address') ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getFormData()->getStreetLine($_i - 1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i) ?>" id="street_<?php /* @escapeNotVerified */ echo $_i ?>" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>

            <div class="field required">
                <label for="city" class="label"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
                <div class="control">
                    <input type="text" name="city" value="<?php echo $block->escapeHtml($block->getFormData()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
                </div>
            </div>

            <div class="field region required">
                <label for="region_id" class="label"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
                <div class="control">
                    <select id="region_id" name="region_id" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="validate-select" style="display:none;">
                        <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
                    </select>
                    <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>" style="display:none;">
                </div>
            </div>

            <div class="field zip required">
                <label for="zip" class="label"><span><?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?></span></label>
                <div class="control">
                    <input type="text" name="postcode" value="<?php echo $block->escapeHtml($block->getFormData()->getPostcode()) ?>" title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
                </div>
            </div>

            <div class="field country required">
                <label for="country" class="label"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
                <div class="control">
                    <?php echo $block->getCountryHtmlSelect() ?>
                </div>
            </div>
            <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
            <?php if ($addressAttributes): ?>
                <?php $addressAttributes->setEntityType('customer_address'); ?>
                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                <?php echo $addressAttributes->setShowContainer(false)->toHtml()?>
            <?php endif;?>
            <input type="hidden" name="default_billing" value="1">
            <input type="hidden" name="default_shipping" value="1">
        </fieldset>

    <?php endif; ?>
    <fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Sign-in Information') ?></span></legend><br>

        <div class="field password required">
            <label for="password" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
            <div class="control">
                <input type="password" name="password" id="password" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" class="input-text" data-validate="{required:true, 'validate-password':true}" autocomplete="off">
            </div>
        </div>
        <div class="field confirmation required">
            <label for="password-confirmation" class="label"><span><?php /* @escapeNotVerified */ echo __('Confirm Password') ?></span></label>
            <div class="control">
                <input type="password" name="password_confirmation" title="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
            </div>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </fieldset>

    <?php if ($showSignupAffiliate == 2) : ?>
        <fieldset class="fieldset create affiliate">
            <legend class="legend"><span><?php echo __('Signup Affiliate Account Information') ?></span></legend><br/>

            <div class="field choice check_affiliate">
                <input type="checkbox" id="check_affiliate"<?php if ($checkAffiliate): ?> checked="checked"<?php endif; ?> name="check_affiliate" title="<?php echo __('Sign up for our Affiliate Program') ?>" class="checkbox" />
                <label for="check_affiliate" class="label"><span><?php echo __('Sign up for our Affiliate Program') ?></span></label>
            </div>

            <div id="form_register">
                <div class="field required">
                    <label for="getway_withdrawn" class="label"><span><?php echo __('Payment Method') ?></span></label>
                    <div class="control">
                        <select id="getway_withdrawn" name="getway_withdrawn" class="required-entry">
                            <option value=""><?php echo __('Please select a payment method') ?></option>
                            <?php $gateways = $_dataHelper->getGatewayStore(); ?>
                            <?php if($gateways) : ?>
                            <?php foreach ($gateways as $gateway) : ?>
                                <?php if (strtolower(trim($gateway['mw_status'])) == 'yes') : ?>
                                    <option<?php if ($paymentGateway == $gateway['gateway_value']):?> selected="selected"<?php endif;?> value="<?php echo $gateway['gateway_value']; ?>"><?php echo $gateway['gateway_title']; ?></option>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                        </select>
                    </div>
                </div>

                <div class="field required" id="mw_paypal_email">
                    <label for="paypal_email" class="label"><span><?php echo __('Payment Email') ?></span></label>
                    <div class="control">
                        <input type="text" name="paypal_email" id="paypal_email" value="<?php echo $paymentEmail;?>" title="<?php echo __('Payment Email') ?>" class="input-text validate-email required-entry" />
                    </div>
                </div>

                <div id="form_account_bank">
                    <div class="field required">
                        <label for="bank_name" class="label"><span><?php echo __('Bank Name') ?></span></label>
                        <div class="control">
                            <input type="text" name="bank_name" id="bank_name" value="<?php echo $bankName;?>" title="<?php echo __('Bank Name') ?>" class="input-text required-entry" />
                        </div>
                    </div>

                    <div class="field required">
                        <label for="name_account" class="label"><span><?php echo __('Name on account') ?></span></label>
                        <div class="control">
                            <input type="text" name="name_account" id="name_account" value="<?php echo $nameAccount;?>" title="<?php echo __('Name on account') ?>" class="input-text required-entry" />
                        </div>
                    </div>

                    <div class="field required">
                        <label for="bank_country" class="label"><span><?php echo __('Bank Country') ?></span></label>
                        <div class="control">
                            <?php echo $block->getCountryHtmlSelect($bankCountry,'bank_country','bank_country','Bank Country') ?>
                        </div>
                    </div>

                    <div class="field required">
                        <label for="swift_bic" class="label"><span><?php echo __('SWIFT code') ?></span></label>
                        <div class="control">
                            <input type="text" name="swift_bic" id="swift_bic" value="<?php echo $swiftBic;?>" title="<?php echo __('SWIFT code') ?>" class="input-text required-entry" />
                        </div>
                    </div>

                    <div class="field required">
                        <label for="account_number" class="label"><span><?php echo __('Account Number') ?></span></label>
                        <div class="control">
                            <input type="text" name="account_number" id="account_number" value="<?php echo $swiftBic;?>" title="<?php echo __('Account Number') ?>" class="input-text required-entry" />
                        </div>
                    </div>

                    <div class="field required">
                        <label for="re_account_number" class="label"><span><?php echo __('Re-enter Account Number') ?></span></label>
                        <div class="control">
                            <input type="text" name="re_account_number" id="re_account_number" value="<?php echo $swiftBic;?>" title="<?php echo __('Re-enter Account Number') ?>" class="input-text required-entry validate-re_account_number" />
                        </div>
                    </div>
                </div>

                <div class="field required">
                    <label for="auto_withdrawn" class="label"><span><?php echo __('Auto Withdrawal') ?></span></label>
                    <div class="control">
                        <select id="auto_withdrawn" name="auto_withdrawn">
                            <?php $autoWithdrawns = \MW\Affiliate\Model\Autowithdrawn::getOptionArray();?>
                            <?php foreach ($autoWithdrawns as $value => $autowithdrawn) : ?>
                            <option<?php if ($autoWithdrawn == $value) : ?> selected="selected"<?php endif; ?> value="<?php echo $value;?>"><?php echo $autowithdrawn;?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <div class="field required" id="payment_release_level_">
                    <?php
                    $max = $_dataHelper->getPricingHelper()->currency($_dataHelper->getWithdrawMaxStore());
                    $min = $_dataHelper->getPricingHelper()->currency($_dataHelper->getWithdrawMinStore());
                    ?>
                    <label for="payment_release_level" class="label"><span><?php echo __('Auto payment when account balance reaches (%1 - %2)', $min, $max)?></span></label>
                    <div class="control">
                        <input type="text" name="payment_release_level" id="payment_release_level" value="<?php echo $withdrawnLevel;?>" title="<?php echo __('Auto payment when account balance reaches') ?>" class="input-text required-entry validate-digits" />
                    </div>
                </div>

                <div class="field">
                    <label for="reserve_level" class="label"><span><?php echo __('Reserve Level (to be kept in account)') ?></span></label>
                    <div class="control">
                        <input type="text" name="reserve_level" id="reserve_level" value="<?php echo $reserveLevel;?>" title="<?php echo __('Reserve Level') ?>" class="input-text validate-digits" />
                    </div>
                </div>

                <div class="field">
                    <label for="referral_site" class="label"><span><?php echo __('Affiliate Website(s)') ?></span></label>
                    <div class="control">
                        <textarea class="input-text" title="<?php echo __('Affiliate Website(s)') ?>" name="referral_site" id="referral_site" ><?php echo $referralSite;?></textarea>
                    </div>
                </div>
            </div>
        </fieldset>
    <?php endif; ?>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Create an Account') ?>"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Back') ?></span></a>
        </div>
    </div>
</form>
<script>
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;

    dataForm.mage('validation', {
    <?php if ($_dob->isEnabled()): ?>
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
    <?php else: ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    <?php endif ?>
    }).find('input:text').attr('autocomplete', 'off');

});
</script>
<?php if ($block->getShowAddressFields()): ?>
    <script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php endif; ?>

<?php if ($isEnabled && $showSignupAffiliate == 2) : ?>
<script>
require([
    'jquery'
], function($) {
    $(document).ready(function() {
        hideForm();

        $('#check_affiliate').on('click', function() {
            hideForm();
        });

        $('#auto_withdrawn').on('change', function() {
            if ($('#auto_withdrawn').val() == '2') {
                $('#payment_release_level_').hide();
            } else {
                $('#payment_release_level_').show();
            }
        });

        $('#getway_withdrawn').on('change', function () {
            if ($('#getway_withdrawn').val() == 'banktransfer') {
                $('#form_account_bank').show();
                $('#mw_paypal_email').hide();
            } else if ($('#getway_withdrawn').val() == 'check') {
                $('#form_account_bank').hide();
                $('#mw_paypal_email').hide();
            } else {
                $('#mw_paypal_email').show();
                $('#form_account_bank').hide();
            }
        });
    });

    function hideForm() {
        if ($('#check_affiliate').is(':checked')) {
            $('#form_register').show();
            $('#form_account_bank').hide();

            if ($('#auto_withdrawn').val() == '2') {
                $('#payment_release_level_').hide();
            } else {
                $('#payment_release_level_').show();
            };

            if ($('#getway_withdrawn').val() == 'banktransfer') {
                $('#form_account_bank').show();
                $('#mw_paypal_email').hide();
            } else if ($('#getway_withdrawn').val() == 'check') {
                $('#form_account_bank').hide();
                $('#mw_paypal_email').hide();
            } else {
                $('#mw_paypal_email').show();
                $('#form_account_bank').hide();
            };
        } else {
            $('#form_register').hide();
        }
    };
});
</script>
<?php endif; ?>