<?php
namespace Magenest\Xero\Model\ResourceModel\CronSchedule;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    /**
     * Initialize resource collection
     *
     * @return void
     */
    protected function _construct()
    {
        $this->_init(\Magenest\Xero\Model\CronSchedule::class, \Magenest\Xero\Model\ResourceModel\CronSchedule::class);
    }

    public function _beforeLoad()
    {
        $this->addFieldToFilter('job_code', 'magenest_xero_sync');
        $this->addOrder('schedule_id');
        return parent::_beforeLoad(); // TODO: Change the autogenerated stub
    }
}
