<?php
/**
 * Copyright © Magenest JSC. All rights reserved.
 *
 * Created by PhpStorm.
 * User: crist
 * Date: 05/12/2019
 * Time: 14:31
 */

namespace Magenest\Xero\Block\System\Config\Form;

use Magenest\Xero\Block\Adminhtml\Connection\Status as ConnectionStatus;
use Magenest\Xero\Helper\Signature;
use Magenest\Xero\Model\CoreConfig;
use Magenest\Xero\Model\Helper;
use Magento\Backend\Block\Template\Context;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\Data\Form\Element\AbstractElement;
use Magento\Store\Model\ScopeInterface;
use Magento\Config\Block\System\Config\Form\Field as ConfigFormField;

class Connection extends ConfigFormField
{
    protected $_config;

    protected $_helper;

    public function __construct(
        CoreConfig $config,
        Context $context,
        Helper $helper,
        array $data = []
    ) {
        $this->_config = $config;
        $this->_helper = $helper;
        parent::__construct($context, $data);
    }

    /**
     * Create element for Access token field in store configuration
     * @param AbstractElement $element
     * @return string
     */
    public function render(AbstractElement $element)
    {
        $element->setInherit(false);
        $element->setCanUseWebsiteValue(false);
        $element->setCanUseDefaultValue(false);
        $element->setCanRestoreToDefault(false);
        $element->setValue($this->isConnected());
        return parent::render($element); // TODO: Change the autogenerated stub
    }

    protected function _getElementHtml(AbstractElement $element)
    {
        $connection = $this->getLayout()->createBlock(ConnectionStatus::class);
        return $element->getElementHtml() . $connection->toHtml();
    }

    protected function isConnected()
    {
        $websiteId = $this->getRequest()->getParam('website');
        if ($websiteId) {
            $scope = ScopeInterface::SCOPE_WEBSITES;
            $this->_helper->setScope($scope);
            $this->_helper->setScopeId($websiteId);
        } else {
            $scope = ScopeConfigInterface::SCOPE_TYPE_DEFAULT;
            $websiteId = 0;
        }

        return $this->_config->getConfigValueByScope(
            Signature::PATH_XERO_OAUTH_V2_IS_CONNECTED,
            $scope,
            $websiteId
        ) ? : 0;
    }
}
