<?php
/**
 * Copyright © 2015 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 *
 * Magenest_Xero extension
 * NOTICE OF LICENSE
 *
 * @category  Magenest
 * @package   Magenest_Xero
 * @author ThaoPV
 */
?>
<?php
/** @var $block \Magenest\Xero\Block\System\Config\Form\Button\Connection */
?>
<?php if ($block->isValidForConnect()): ?>
<div class="actions button-container">
    <button  class="button"
             type="button"
             data-role="<?= /* @escapeNotVerified */ $block->getHtmlId() ?>"
             id="<?= /* @escapeNotVerified */ $block->getHtmlId() ?>"
        <?= $block->escapeHtml($block->isClientIdExist() ? '' : 'disabled') ?>>
        <span><?= /* @escapeNotVerified */ $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <div id="result" data-role="result-check" class="message-validation hide"></div>
</div>
<script>
    require(['jquery'], function($){
        'use strict';
        var buttonDataRole = $('[data-role="<?= /* @escapeNotVerified */ $block->getHtmlId()?>"]');
        buttonDataRole.click(function(){
            window.open("<?= $block->getOAuthUrl() ?>",
                "_blank", "toolbar=yes,scrollbars=yes,resizable=yes,top=300,left=600,width=800,height=640");
        });
    });
</script>
<?php else: ?>
    <p class="note" style="color: red"><span><?= $block->escapeHtml($block->getErrorMessage()) ?></span></p>
<?php endif; ?>
