<?php
namespace Magenest\Xero\Model\ResourceModel\Log;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    /**
     * Initialize resource collection
     *
     * @return void
     */
    protected function _construct()
    {
        $this->_init(\Magenest\Xero\Model\Log::class, \Magenest\Xero\Model\ResourceModel\Log::class);
    }

    protected function _initSelect()
    {
        parent::_initSelect(); // TODO: Change the autogenerated stub

        $joinTable = $this->getTable('magenest_xero_xml_log');
        return $this->getSelect()->joinLeft(
            ['xml_log' => $joinTable],
            "main_table.xml_log_id = xml_log.id",
            ['scope', 'scope_id', 'xml_log_table_id' => 'xml_log.id']
        );
    }
    public function addFieldToFilter($field, $condition = null)
    {
        if ($field == 'id') {
            $field = 'main_table.id';
        }
        if ($field == 'type') {
            $field = 'main_table.type';
        }
        if ($field == 'scope_id') {
            $field = 'xml_log.scope_id';
        }
        return parent::addFieldToFilter($field, $condition);
    }
}
