<?php
namespace Magenest\Xero\Model;

use Magento\Framework\Model\Context;
use Magento\Framework\Model\ResourceModel\AbstractResource;

class PaymentMapping extends \Magento\Framework\Model\AbstractModel
{
    protected $_helper;

    public function __construct(
        Context $context,
        \Magento\Framework\Registry $registry,
        Helper $helper,
        AbstractResource $resource = null,
        \Magento\Framework\Data\Collection\AbstractDb $resourceCollection = null,
        array $data = []
    ) {
        $this->_helper = $helper;
        parent::__construct($context, $registry, $resource, $resourceCollection, $data);
    }

    /**
     * Init
     */
    protected function _construct()
    {
        $this->_init(\Magenest\Xero\Model\ResourceModel\PaymentMapping::class);
    }

    /**
     * @param $paymentCode
     * @param $scopeId
     * @return bool|PaymentMapping
     */
    public function loadByPaymentCode($paymentCode, $scopeId = 0)
    {
        $scopes = [$this->_helper->getScope()];
        $scopeIds = [$this->_helper->getScopeId()];

        if (!$this->_helper->isMultipleWebsiteEnable()) {
            $scopes[] = 'websites';
            $scopeIds[] = $scopeId;
        }
        /** @var PaymentMapping $mapping */
        $mapping = $this->getCollection()
            ->addFieldToFilter('payment_code', $paymentCode)
            ->addFieldToFilter('scope', $scopes)
            ->addFieldToFilter('scope_id', $scopeIds)
            ->setOrder('scope_id')
            ->getFirstItem();
        if ($mapping->getId()) {
            return $mapping;
        }
        return false;
    }

    public function beforeSave()
    {
        $this->setData('scope', $this->_helper->getScope());
        $this->setData('scope_id', $this->_helper->getScopeId());
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }
}
