<?php
namespace Magenest\Xero\Model;

use Magento\Framework\Model\Context;
use Magento\Framework\Model\ResourceModel\AbstractResource;

class TaxMapping extends \Magento\Framework\Model\AbstractModel
{
    protected $_helper;
    public function __construct(
        Context $context,
        \Magento\Framework\Registry $registry,
        Helper $helper,
        AbstractResource $resource = null,
        \Magento\Framework\Data\Collection\AbstractDb $resourceCollection = null,
        array $data = []
    ) {
        $this->_helper = $helper;
        parent::__construct($context, $registry, $resource, $resourceCollection, $data);
    }

    /**
     * Init
     */
    protected function _construct()
    {
        $this->_init(\Magenest\Xero\Model\ResourceModel\TaxMapping::class);
    }

    /**
     * @param $taxCode
     * @return bool|TaxMapping
     */
    public function loadByTaxCode($taxCode)
    {
        /** @var TaxMapping $mapping */
        $mapping = $this->getCollection()
            ->addFieldToFilter('tax_id', $taxCode)
            ->addFieldToFilter('scope', $this->_helper->getScope())
            ->addFieldToFilter('scope_id', $this->_helper->getScopeId())
            ->getFirstItem();
        if ($mapping->getId()) {
            return $mapping;
        }
        return false;
    }

    public function beforeSave()
    {
        $this->setData('scope', $this->_helper->getScope());
        $this->setData('scope_id', $this->_helper->getScopeId());
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }
}
