<?php
namespace Magenest\Xero\Controller\Adminhtml\MassSync;

use Magento\Framework\App\Action\Action;
use Magento\Framework\App\Action\Context;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\Controller\ResultFactory;
use Magento\Ui\Component\MassAction\Filter;
use Magenest\Xero\Model\Helper;
use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;
use Magenest\Xero\Model\Synchronization;
use Magenest\Xero\Model\QueueFactory;
use Magento\Framework\Data\Collection\AbstractDb;

abstract class AbstractMassSync extends Action
{
    protected $_config;

    protected $_filter;

    protected $_enable = "";

    protected $_helper;

    protected $_collectionFactory;

    protected $_id;

    protected $_queueFactory;

    protected $_syncModel;

    public function __construct(
        QueueFactory $queueFactory,
        Context $context,
        ScopeConfigInterface $config,
        Filter $filter,
        Helper $helper,
        AbstractDb $collectionFactory,
        Synchronization $syncModel
    ) {
        $this->_syncModel = $syncModel;
        $this->_queueFactory = $queueFactory;
        $this->_collectionFactory = $collectionFactory;
        $this->_config = $config;
        $this->_filter = $filter;
        $this->_helper = $helper;
        parent::__construct($context);
    }

    /**
     * @param RequestInterface $request
     * @return \Magento\Framework\App\ResponseInterface|\Magento\Framework\Controller\ResultInterface
     * @throws \Magento\Framework\Exception\NotFoundException
     */
    public function dispatch(RequestInterface $request)
    {
        try {
            $enable = $this->_config->getValue($this->_enable);
            if ($enable) {
                return parent::dispatch($request); // TODO: Change the autogenerated stub
            } else {
                return $this->handleUnauthorizedRequest();
            }
        } catch (\Exception $exception) {
            $this->messageManager->addErrorMessage("Can't handle the request. Error: ".$exception->getMessage());
            return $this->redirectBack();
        }
    }

    protected function handleUnauthorizedRequest()
    {
        if ($this->getRequest()->isAjax()) {
            $result = [
                'error' => true,
                'msg' => 'We could not handle your request. Please try again!'
            ];
            $response = $this->resultFactory->create(ResultFactory::TYPE_JSON);
            $response->setData($result);
            return $response;
        }
        $this->messageManager->addError('We could not handle your request. Please try again!');
        $resultRedirect = $this->resultFactory->create(ResultFactory::TYPE_REDIRECT);
        $resultRedirect->setUrl($this->_redirect->getRefererUrl());
        return $resultRedirect;
    }
    public function execute()
    {
        $collection = $this->_filter->getCollection($this->_collectionFactory);

        $queueModel = $this->_queueFactory->create();
        $connection = $queueModel->getResource()->getConnection();
        /** @var \Magento\Backend\Model\View\Result\Redirect $resultRedirect */
        $resultRedirect = $this->resultRedirectFactory->create();
        $ids = [];
        foreach ($collection as $item) {
            $ids[] = $item->getData($this->_id);
            if (count($ids) > 1000) {
                if ($this->_helper->isXeroConnectedByIds($ids, $this->_collectionFactory, $this->_id)) {
                    $this->messageManager
                        ->addErrorMessage('Please connect the integration to your Xero account first!');
                    return $resultRedirect->setPath($this->_redirect->getRefererUrl());
                };
                if ($this->_helper->isMultipleWebsiteEnable()) {
                    $this->_syncModel->addRecordsForMultipleWebsite($ids, $connection, $queueModel);
                } else {
                    $this->_syncModel->addRecords($ids, $connection, $queueModel);
                }
                $ids = [];
            }
        }
        if (count($ids)) {
            if (!$this->_helper->isXeroConnectedByIds($ids, $this->_collectionFactory, $this->_id)) {
                $this->messageManager->addErrorMessage('Please connect the integration to your Xero account first!');
                return $resultRedirect->setPath($this->_redirect->getRefererUrl());
            };
            if ($this->_helper->isMultipleWebsiteEnable()) {
                $this->_syncModel->addRecordsForMultipleWebsite($ids, $connection, $queueModel);
            } else {
                $this->_syncModel->addRecords($ids, $connection, $queueModel);
            }
        }
        if ($this->_helper->getRegistry('sync_error'))
        {
            $this->messageManager->addWarningMessage(
                __('%1 item(s) cannot be synced, check out Logs for details.', $this->_helper->getRegistry('sync_error'))
            );
        } else {
            $this->messageManager->addSuccessMessage(__('A total of %1 record(s) have been synced.', $collection->getSize()));
        }
    }
    protected function redirectBack()
    {
        $resultRedirect = $this->resultFactory->create(ResultFactory::TYPE_REDIRECT);
        return $resultRedirect->setPath($this->_redirect->getRefererUrl());
    }
}
