<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Rmasystem
 * @author    Webkul Software Private Limited
 * @copyright Copyright (c)  Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<form id="edit_form" data-order-config='<?= /* @noEscape */ $block->getOrderDataJson() ?>' 
    data-load-base-url="<?= /* @noEscape */ $block->getLoadBlockUrl() ?>" 
    action="<?= /* @noEscape */ $block->getSaveUrl() ?>" 
    method="post" 
    enctype="multipart/form-data">
    
</form>